### PR TITLE
Fix for Issue #73: findScrollableParent false positives in IE

### PR DESCRIPTION
**Pull request by robertmorgan**
### About
IE has rounding bug, where a calculated height can be rounded down to the nearest whole pixel `clientHeight` and is rounded up for `scrollHeight`. This causes  the`hasScrollableSpace` check within `findScrollableParent`, which compares these two values for a given element, to sometimes return a false positive.

### Changes
- Proposed fix for #73 by detecting the current user agent and applying a tolerance where appropriate.
- Fixes pre-existing linting error for line length in master.
- Add the [default `npm-debug.log` filename](https://docs.npmjs.com/misc/config#loglevel) to `.gitignore`

### CODE REVIEW

**Comment by robertmorgan** [comment]
@iamdustan - Is there any chance that you could take a look at this Pull Request so that we can get the IE11 issue fixed?

Thanks.
Rob M.

**Comment by jeremenichelli** [comment]
Sorry for the long wait Robert. I will take a look at this and merge after some repo review.

**Comment by jeremenichelli** [comment]
Is it possible to remove the dist file from the diff? Thanks.

**Comment by robertmorgan** [comment]
@jeremenichelli, sure no problem. That's now done.

**Comment by jeremenichelli** [comment]
Thanks! Sadly, this PR and others are entering in conflict (https://github.com/iamdustan/smoothscroll/pull/45/files) so I'm gonna manually pick up the work of each to simplify the release and be equally fair with everyone since someone would need to resolve the conflicts no matter the other I chose.

I'm gonna make a PR and put you as a reviewer so you can check your changes.

**Pull request merged**
