### PR TITLE
Add scrollend and stopscroll event handling

### PR DESCRIPTION
**Pull request by Filip-rspective**

### CODE REVIEW

**Comment by iamdustan** [comment]
I can’t find any references to these in any specs. Could you provide a link to any spec proposals for this?

**Comment by Filip-rspective** [comment]
Hello,

I have extended docs. I hope this is enough.

Filip

**Comment by jeremenichelli** [comment]
Hi @Filip-rspective, thanks for the PR. 

I can understand the need of having a `stopscroll` event, but this is a polyfill relying on an official spec, so to merge it we need to make sure this is part of the expected native behavior.

Imaging adding this in a browser that natively supports the spec and throwing an error when the event is dispatched, or not causing the expected behavior for example.

Let me know if you have further questions.

**Comment by alexhisen** [comment]
We have found that native smooth scroll behavior on latest Chrome for example is way too fast compared to the polyfill at least for very small scroll distances, so relying on native behavior may not be workable anyway, hence the existence of __forceSmoothScrollPolyfill__.

It's easy to document that the extra event capabilities are only available if you use  __forceSmoothScrollPolyfill__ = true. With that nobody would be surprised, but a lot of devs will find these extra capabilities useful (it becomes trivial to implement an abort of smooth scroll in progress upon touchstart).

And devs who simply expect this to work as 100% standards-compliant polyfill will not use these events and nothing will change for them.

**Comment by iamdustan** [comment]
We’re not in the business of extending or supporting things outside the scope of the spec. Even the current ability we provide to force the polyfill is a big questionable.

**Comment by jeremenichelli** [comment]
> We’re not in the business of extending or supporting things outside the scope of the spec

Second this.

**Pull request closed without merging**
