### PR TITLE
works with browser inconsistency of documentElement vs body scroll

### PR DESCRIPTION
**Pull request by ThiRaBrTNK**
`element.scrollIntoView` didn't work in webkit(blink)-based browsers because you need to change scrollTop of body, not documentElement for document to get scrolled in them. There is a good reading about reasons: https://miketaylr.com/posts/2014/11/document-body-scrollTop.html. This bug may be the same to #2, but I'm not sure.

### CODE REVIEW

**Comment by iamdustan** [comment]
Sorry for the delay, @ThiRaBrTNK. Could you rebase this and then I’ll test it out? Cheers!

**Comment by ThiRaBrTNK** [comment]
I've updated the repo. I've added failing conditions to test.html so you can see the problem that is solved in this PR.

**Comment by stevenvachon** [comment]
Can this get merged or what?

**Comment by stevenvachon** [comment]
@iamdustan can this get merged or what?

**Comment by stevenvachon** [comment]
@ThiRaBrTNK I'm confused -- this isn't working for me in webkit/blink browsers.

**Comment by ThiRaBrTNK** [comment]
@stevenvachon If you need this fix, you can switch to my fork with `bower install https://github.com/ThiRaBrTNK/smoothscroll.git`

**Comment by jeremenichelli** [comment]
@ThiRaBrTNK sorry for the long silence, I'm a contributor of this repo. I'm addressing this issue and as soon as I check everything I'll merge this or elave a comment. Thanks for your patience.

**Comment by jeremenichelli** [comment]
@iamdustan this seems to be correct, and should be merged. Putting this comment so you can give it a last glance before merging, it has my **+1**.

**Comment by ThiRaBrTNK** [comment]
@jeremenichelli No problem, I simply have my fork in dependencies while it's not fixed ;)
@stevenvachon Could you please elaborate on what exactly isn't working?

**Comment by stevenvachon** [comment]
@ThiRaBrTNK `scrollIntoView`. Removing my second comment.

**Comment by jeremenichelli** [comment]
Merging this, thanks for the help and sorry for the wait.

**Comment by ThiRaBrTNK** [comment]
@stevenvachon There probably are more issues with it (`scrollIntoView ` is marked with "incomplete" on the main page). My PR is only fixing particular `documentElement` issue.

**Pull request merged**
