### PR TITLE
Fix scrolling to an element inside of a scrollable container

### PR DESCRIPTION
**Pull request by DylanPiercey**
This allows for scrollIntoView to work with elements that are not visible in the window and have a scrollable parent that isnt the window. (Both will scroll with different animation frames).

### CODE REVIEW

**Comment by iamdustan** [comment]
Could you add an example html file to demonstrate this?

**Comment by jeremenichelli** [comment]
And example on the html file we have in the repo would be good. I think I did notice this bug @iamdustan but I haven't check that for quite a long time.

@DylanPiercey if you can provide a test case on the html test file so we can reproduce it in master branch.

**Comment by DylanPiercey** [comment]
Sorry I am in vacation and won't be able to fix the PR for a couple weeks.

**Comment by jeremenichelli** [comment]
Not a problem @DylanPiercey, have a good rest and come back when ready.

**Comment by jeremenichelli** [comment]
@DylanPiercey a major refactor just got merged addressing this issue around `scrollIntoView`, thanks for reporting this.

**Pull request closed without merging**
